comment:
  behavior: default
  require_changes: false # if true: only post the comment if coverage changes
  hide_project_coverage: false # [true :: only show coverage on the git diff aka patch coverage]]
