name: Build Warp

on:
  push:

jobs:
  build-warp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade numpy
      - name: Build
        run: |
          python build_lib.py
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            warp/bin/**/*.dll
            warp/bin/**/*.so
            warp/bin/**/*.dylib

  test-warp:
    runs-on: ubuntu-latest
    needs: build-warp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Download Warp build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: warp/bin/
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade numpy
          pip install .
      - name: Run tests
        run: python -m warp.tests --junit-report-xml rspec.xml --coverage --coverage-xml coverage.xml -s autodetect
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "coverage.xml"
          show: "fail, skip"
        if: always()
