name: Build Warp

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-warp-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade numpy
      - name: Build
        run: |
          tools/packman/packman install -l _build/target-deps/cuda cuda 11.8.0_522.06-abe3d9d7-windows-x86_64
          python build_lib.py --cuda_path=_build/target-deps/cuda
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-windows
          path: |
            warp/bin/**/*.dll

  build-warp-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade numpy
      - name: Build
        run: |
          tools/packman/packman install -l _build/target-deps/cuda cuda 11.8.0_520.61-d8963068-linux-x86_64
          python build_lib.py --cuda_path=_build/target-deps/cuda
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-ubuntu
          path: |
            warp/bin/**/*.so
            warp/bin/**/*.dylib

  build-warp-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade numpy
      - name: Build
        run: |
          python build_lib.py
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-macos
          path: |
            warp/bin/**/*.so
            warp/bin/**/*.dylib

  test-warp-windows:
    runs-on: windows-latest
    needs: build-warp-windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Download Warp build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact-windows
          path: warp/bin/
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade numpy coverage[toml] usd-core
          pip install .
      - name: Run Tests
        run: python -m warp.tests --junit-report-xml rspec.xml -s autodetect

  test-warp-ubuntu:
    runs-on: ubuntu-latest
    needs: build-warp-ubuntu
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Download Warp build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact-ubuntu
          path: warp/bin/
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade numpy coverage[toml] usd-core
          pip install .
      - name: Run Tests
        run: python -m warp.tests --junit-report-xml rspec.xml -s autodetect
      - name: Test Summary
        uses: test-summary/action@v2.3
        with:
          paths: "rspec.xml"
          show: "all"
        if: always()
      - name: Upload Test Summary
        uses: actions/upload-artifact@v4
        with:
          name: test-summary
          path: |
            test-summary.md
            rspec.xml
        if: always()
