# Nightly workflow only runs on the default branch
name: nightly

on:
  schedule:
    - cron: "45 9 * * *" # 7AM UTC, 12AM PST, 3AM EST

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
