name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"
  pull_request: # Remove when using nv-gha-runners

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check Code Format
        uses: pre-commit/action@v3.0.1
        continue-on-error: true # Testing only, remove later
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
