name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"
  pull_request: # Remove when using nv-gha-runners

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
